version: "3.8"

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: flask-starter-kit
    container_name: flask-starter-kit
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    command: "python -m api.wsgi"
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
      - FLASK_DEBUG_MODE=${FLASK_DEBUG_MODE:-true}
      - PYTHONBREAKPOINT=ipdb.set_trace
    volumes:
      - ./api:/app/api

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    image: flask-starter-kit
    container_name: flask-starter-kit-prod
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    command: gunicorn --bind "0.0.0.0:${FLASK_PORT:-5000}" api.wsgi:app
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
      - FLASK_DEBUG_MODE=false
    volumes:
      - ./api:/app/api
